# code: language=ansible
---
- name: Update package manager
  become: true
  ansible.builtin.package:
    update_cache: true
  tags:
    - pkg

- name: Install softwares with package manager
  become: true
  ansible.builtin.package:
    name:
      "{{ kubya_packages }}"
  register: result
  when: ansible_pkg_mgr != "pacman"
  ignore_errors: true
  tags:
    - pkg

- name: Make ~/.ssh Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    group: root
    owner: root
  loop:
    - "~/.ssh"
  register: result
  tags: ssh

- name: Touch config of the ssh
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: touch
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ sshconfig }}"
      mode: '0600'
  ignore_errors: true
  tags: ssh

- name: Make ~/.ssh/id_rsa and ~/.ssh/id_rsa.pub
  become: true
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    mode: '0400'
    content: |
      {{ item.content }}
  loop:
    - dest: "{{ ssh_key }}"
      content: "{{ enc_id_rsa_key }}"
    - dest: "{{ ssh_pub }}"
      content: "{{ enc_id_rsa_pub }}"
  when: enc_id_rsa_key is not undefined and enc_id_rsa_pub is not undefined
  register: result
  tags: ssh

- name: Print variables
  ansible.builtin.debug:
    var: result
  tags: ssh

- name: Make ~/.kube Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    group: root
    owner: root
  loop:
    - "~/.kube"
  register: result
  when: use_kube
  tags: kube

- name: Touch config of the kube
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: touch
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ kubeconfig }}"
      mode: '0400'
  ignore_errors: true
  when: use_kube
  tags: kube

- name: Clone a Git repository with authentication
  ansible.builtin.git:
    repo: '{{ item.from }}'
    dest: "{{ item.to }}"
    clone: true
    depth: 1
    recursive: true
    version: '{{ item.version }}'
    accept_hostkey: true
    force: true
    update: true
  with_items:
    - { from: 'https://{{ enc_gh_user }}:{{ enc_gh_token }}@github.com/{{ enc_gh_user }}/kubya.git', to: '{{ local_ws }}/kubya', version: 'dev' }
    - { from: 'https://{{ enc_gh_user }}:{{ enc_gh_token }}@github.com/{{ enc_gh_user }}/kubya-playbooks.git', to: '{{ local_ws }}/playbooks', version: 'dev' }
    - { from: 'https://{{ enc_gh_user }}:{{ enc_gh_token }}@github.com/{{ enc_gh_user }}/jenkins-docker.git', to: '{{ local_ws }}/jenkins-docker', version: 'dev' }
  when: git_clone
  tags:
    - git_clone
    - sync

# - name: Check .gitconfig
#   ansible.builtin.stat:
#     path: "~/.gitconfig"
#   register: res_gitconf
#   tags: zshenv

# - name: Replace {{ gitconf }}
#   ansible.builtin.lineinfile:
#     path: "{{ gitconf }}"
#     regexp: "{{ item.regexp }}"
#     line: "{{ item.line }}"
#     state: present
#     backup: false
#   with_items:
#     - { regexp: "name.=.", line: "    name = {{ git_user }}" }
#     - { regexp: "email.=.", line: "    email = {{ git_user_email }}" }
#   when: res_gitconf.stat.exists and git_user
#   register: result
#   tags: zshenv

- name: Make Directory [user_local, user_bin and etc]
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    group: root
    owner: root
  with_items:
    - "{{ config_zsh if ansible_user_shell == '/usr/bin/zsh' else config_bash }}"
    - "{{ user_local }}"
    - "{{ local_bin }}"
    - "{{ local_ws }}"
  register: result

# - name: Copy user scripts for zsh
#   ansible.builtin.copy:
#     src: '{{ item.from }}'
#     dest: '{{ item.to }}'
#     mode: '0644'
#   with_items:
#     - { from: '{{ local_ws }}/kubya/ansible/files/HOME/.zshrc', to: '{{ config_zsh }}' }
#     - { from: '{{ local_ws }}/kubya/ansible/files/HOME/.config/zsh/.zshenv', to: '{{ config_zsh }}' }
#   when: ansible_user_shell == "/usr/bin/zsh"
#   tags:
#     - sync
#     - zsh

# - name: Copy user scripts for bash
#   ansible.builtin.copy:
#     src: '{{ item.from }}'
#     dest: '{{ item.to }}'
#     mode: '0644'
#   with_items:
#     - { from: '{{ local_ws }}/kubya/ansible/files/HOME/.bashrc', to: '{{ config_bash }}' }
#     - { from: '{{ local_ws }}/kubya/ansible/files/HOME/.config/bash/.bashenv', to: '{{ config_bash }}' }
#     - { from: '{{ local_ws }}/kubya/ansible/files/HOME/.config/bash/bashalias.sh', to: '{{ config_bash }}' }
#   when: ansible_user_shell != "/usr/bin/zsh"
#   tags:
#     - sync
#     - bash

# - name: Copy user configs
#   ansible.builtin.copy:
#     src: '{{ item }}'
#     dest: '{{ config_zsh if ansible_user_shell == "/usr/bin/zsh" else config_bash }}/'
#     mode: '0644'
#   with_fileglob:
#     - '{{ local_ws }}/kubya/ansible/files/HOME/.config/zsh/*'
#   tags:
#     - sync
#     - bash
#     - zsh

# - name: Copy localbin
#   ansible.builtin.copy:
#     src: '{{ item }}'
#     dest: '{{ local_bin }}/'
#     mode: '0644'
#   with_fileglob:
#     - '{{ local_ws }}/kubya/ansible/files/HOME/.local/bin/*'
#   tags:
#     - sync

# - name: Check {{ zshenv }}
#   ansible.builtin.stat:
#     path: "{{ zshenv }}"
#   register: exist_zshenv

# - name: Replace {{ zshenv }}
#   become: true
#   ansible.builtin.lineinfile:
#     path: "{{ zshenv }}"
#     regexp: '{{ item.from }}'
#     line: '{{ item.to }}'
#     state: present
#     backup: false
#   with_items:
#     - { from: 'export GHCR_USERNAME', to: 'export GHCR_USERNAME="{{ dkr_username }}"' }
#     - { from: '^(#.)?export CR_PAT', to: 'export CR_PAT="{{ dkr_passwd }}"' }
#     - { from: '^(#.)?export SSHPW', to: 'export SSHPW="{{ ansible_ssh_pass }}"' }
#     # - { from: 'export DKR_USERNAME', to: 'export DKR_USERNAME="{{ dkr_username }}"' }
#     # - { from: '^(#.)?export DKR_PASSWD', to: 'export DKR_PASSWD="{{ dkr_passwd }}"' }
#   when: exist_zshenv.stat.exists
#   register: result
#   ignore_errors: true
#   tags: zshenv

# - name: Print variables
#   ansible.builtin.debug:
#     var: result

# - name: Find all .sh files in workspace directory
#   ansible.builtin.find:
#     paths: "{{ item }}"
#     patterns: "*.sh"
#     hidden: true
#     recurse: true
#     use_regex: false
#   loop:
#     - "{{ local_bin }}"
#     - "{{ local_ws }}"
#   register: sh_files

# - name: Print variables
#   ansible.builtin.debug:
#     var: sh_files

# - name: Change permissions of .sh files
#   ansible.builtin.file:
#     path: "{{ item.path }}"
#     mode: "u+x"
#   loop: "{{ sh_files.results | map(attribute='files') | flatten }}"


- name: Chezmoi Apply on ArchLinux
  become: true
  ansible.builtin.shell: |
    chezmoi init --apply {{ github_username }}
  register: result
  when: ansible_pkg_mgr == "pacman"

- name: Chezmoi Apply on Linux
  become: true
  ansible.builtin.shell: |
    sh -c "$(curl -fsLS get.chezmoi.io)"
  ags:
    chdir: "/root"
  register: result
  when: ansible_pkg_mgr != "pacman"

- name: Print variables
  ansible.builtin.debug:
    var: result

- name: Change permissions of files and directories
  ansible.builtin.file:
    path: "{{ local_ws }}"
    mode: "0755"
    recurse: true
    state: directory

- name: Check config.yml of the k9s
  ansible.builtin.stat:
    path: "{{ k9s_config }}"
  register: exist_k9s
  tags: k9s

- name: Replace {{ k9s_config }}
  become: true
  ansible.builtin.lineinfile:
    path: "{{ k9s_config }}"
    regexp: '{{ item.from }}'
    line: '{{ item.to }}'
    state: present
    backup: false
  with_items:
    - { from: 'tail: 100', to: '    tail: {{ k9s_tail }}' }
  when: exist_k9s.stat.exists
  register: result
  ignore_errors: true
  tags: k9s

- name: Symbolic link for debian
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "/usr/bin/batcat", dest: "/usr/bin/bat" }
    - { src: "/usr/bin/fdfind", dest: "/usr/bin/fd" }
  when: ansible_facts['os_family'] == "Debian"
  register: result

- name: Make .ansible directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    group: root
    owner: root
  with_items:
    - "~/.ansible"
  register: result

- name: Make aval_password of the ansible
  become: true
  ansible.builtin.copy:
    dest: "{{ aval_pw_file }}"
    content: |
      {{ enc_aval_pw }}
  register: result
  ignore_errors: true

- name: Print variables
  ansible.builtin.debug:
    var: result
